# TikTok Data Collection using Hashtags

This notebook collects public TikTok posts related to the following hashtags:

- #ghibliart
- #ghiblistyle
- #ghiblistudio
- #ghiblitrend

The collected data will be used for future analysis as part of the **GenAI Carbon Footprint Research Project**.

In [3]:
!pip -q install apify-client pandas matplotlib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.3/141.3 kB 3.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 54.0 MB/s eta 0:00:0000:0100:01

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
from apify_client import ApifyClient
import getpass

In [5]:
APIFY_TOKEN = getpass.getpass("Enter Apify API Token: ")

client = ApifyClient(APIFY_TOKEN)

print("✅ Connected to Apify")

Enter Apify API Token:  ········

✅ Connected to Apify

In [6]:
hashtags = [
    "ghibliart",
    "ghiblistyle",
    "ghiblistudio",
    "ghiblitrend"
]

print("Hashtags to collect:")

for tag in hashtags:
    print("-", tag)

Hashtags to collect:
- ghibliart
- ghiblistyle
- ghiblistudio
- ghiblitrend

In [7]:
run_input = {
    "hashtags": hashtags,
    "resultsPerPage": 100
}

print("Starting TikTok scraper...")

run = client.actor("clockworks/tiktok-hashtag-scraper").call(
    run_input=run_input
)

print("✅ Scraping completed.")

Starting TikTok scraper...

[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message:
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:27.307Z ACTOR: Pulling container image of build Sw6Wd8n3lBKw2xWDY from registry.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:27.309Z ACTOR: Creating container.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:27.394Z ACTOR: Starting container.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:27.396Z ACTOR: Running under "LIMITED_PERMISSIONS".
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:27.569Z Running on architecture: x86_64
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:27.571Z Will run command: xvfb-run -a -s "-ac -screen 0 1920x1080x24+32 -nolisten tcp" /bin/bash -o pipefail -c bash -c "    java         --enable-native-access=ALL-UNNAMED         -cp classes-test:classes-main:lib/*         com.zhiliaoapp.musically.MetaSec         > /dev/null &     node dist/src/entrypoint.js "
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:28.519Z INFO  System info {"apifyVersion":"3.7.0","apifyClientVersion":"2.23.0","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v24.18.0"}
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Starting the crawler.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:29.172Z INFO  CheerioCrawler: Starting the crawler.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:31.603Z INFO  [HASHTAG_CONTINUATION] Scraped 29 videos --- https://www.tiktok.com/tag/ghibliart
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:33.528Z INFO  [HASHTAG_CONTINUATION] Scraped 30 videos --- https://www.tiktok.com/tag/ghiblistudio
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:33.900Z INFO  [HASHTAG_CONTINUATION] Scraped 25 videos --- https://www.tiktok.com/tag/ghiblistudio
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:35.023Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Failed to parse TikTok response: Unexpected end of JSON input --- https://www.tiktok.com/tag/ghiblitrend
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:35.025Z     at makeWebApiCall (file:///home/myuser/dist/src/tools/api/web/make-web-api-call.js:114:23) {"id":"3tnRIXn8wcy9mMz","url":"https://www.tiktok.com/tag/ghiblitrend","retryCount":1}
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:35.113Z INFO  [HASHTAG_CONTINUATION] Scraped 16 videos --- https://www.tiktok.com/tag/ghibliart
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:35.842Z INFO  [HASHTAG_CONTINUATION] Scraped 29 videos --- https://www.tiktok.com/tag/ghiblitrend
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:35.974Z WARN  CheerioCrawler: Reclaiming failed request back to the list or queue. Failed to parse TikTok response: Unexpected end of JSON input --- https://www.tiktok.com/tag/ghibliart
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:35.975Z     at makeWebApiCall (file:///home/myuser/dist/src/tools/api/web/make-web-api-call.js:114:23) {"id":"CpE9H4mDz44zRKw","url":"https://www.tiktok.com/tag/ghibliart","retryCount":1}
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:38.031Z INFO  [HASHTAG_CONTINUATION] Scraped 30 videos --- https://www.tiktok.com/tag/ghiblistyle
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Scraped 0/4 hashtags
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:39.033Z INFO  [Status message]: Scraped 0/4 hashtags
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Crawled 10/30 pages, 0 failed requests, desired concurrency 10.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:40.054Z INFO  [HASHTAG_CONTINUATION] Scraped 26 videos --- https://www.tiktok.com/tag/ghiblistyle
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:40.445Z INFO  [HASHTAG_CONTINUATION] Scraped 9 videos --- https://www.tiktok.com/tag/ghiblistudio
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:41.761Z INFO  [HASHTAG_CONTINUATION] Scraped 19 videos --- https://www.tiktok.com/tag/ghibliart
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:41.820Z INFO  [HASHTAG_CONTINUATION] Scraped 5 videos --- https://www.tiktok.com/tag/ghiblistudio
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:42.517Z INFO  [HASHTAG_CONTINUATION] Scraped 19 videos --- https://www.tiktok.com/tag/ghiblistyle
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:43.116Z INFO  [HASHTAG_CONTINUATION] Scraped 19 videos --- https://www.tiktok.com/tag/ghiblistudio
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:43.396Z INFO  [HASHTAG_CONTINUATION] Scraped 15 videos --- https://www.tiktok.com/tag/ghiblistudio
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:43.838Z INFO  [HASHTAG_CONTINUATION] Scraped 7 videos --- https://www.tiktok.com/tag/ghibliart
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:44.954Z INFO  [HASHTAG_CONTINUATION] Scraped 10 videos --- https://www.tiktok.com/tag/ghibliart
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:45.854Z INFO  [HASHTAG_CONTINUATION] Scraped 12 videos --- https://www.tiktok.com/tag/ghiblistyle
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:46.030Z INFO  [HASHTAG_CONTINUATION] Scraped 4 videos --- https://www.tiktok.com/tag/ghiblistyle
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:46.465Z INFO  [HASHTAG_CONTINUATION] Scraped 15 videos --- https://www.tiktok.com/tag/ghiblistyle
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Crawled 26/40 pages, 0 failed requests, desired concurrency 11.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:49.033Z INFO  [Status message]: Scraped 0/4 hashtags
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:49.687Z INFO  [HASHTAG_CONTINUATION] Scraped 6 videos --- https://www.tiktok.com/tag/ghiblistyle
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:50.594Z INFO  [HASHTAG_CONTINUATION] Scraped 26 videos --- https://www.tiktok.com/tag/ghiblitrend
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:52.271Z INFO  [HASHTAG_CONTINUATION] Scraped 27 videos --- https://www.tiktok.com/tag/ghiblitrend
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> 2026-07-09T05:15:54.567Z INFO  [HASHTAG_CONTINUATION] Scraped 25 videos --- https://www.tiktok.com/tag/ghiblitrend
Exception in thread Thread-6 (_stream_log):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/apify_client/_streamed_log.py", line 149, in _stream_log
    for data in log_stream.iter_bytes():
                ^^^^^^^^^^^^^^^^^^^^^^^
impit.TimeoutException: Request timeout (unknown) exceeded.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Scraped 0/4 hashtags
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Crawled 32/42 pages, 0 failed requests, desired concurrency 12.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Crawled 35/43 pages, 0 failed requests, desired concurrency 13.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Crawled 39/43 pages, 0 failed requests, desired concurrency 13.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Crawled 42/43 pages, 0 failed requests, desired concurrency 13.
[apify.tiktok-hashtag-scraper runId:R8WG8g0skgAxbuxoJ] -> Status: RUNNING, Message: Scraped 0/4 hashtags

✅ Scraping completed.

In [8]:
dataset_id = run.default_dataset_id

items = list(
    client.dataset(dataset_id).iterate_items()
)

tiktok_df = pd.DataFrame(items)

print(f"Collected {len(tiktok_df)} posts.")

display(tiktok_df.head())

Collected 400 posts.

,id,text,textLanguage,createTime,createTimeISO,isAd,authorMeta,musicMeta,webVideoUrl,videoMeta,...,hashtags,effectStickers,isSlideshow,isPinned,isSponsored,mediaUrls,input,searchHashtag,commentsDatasetUrl,locationMeta
0,7659146694608801027,How to draw in studio ghibli art style. I see ...,en,1783284065,2026-07-05T20:41:05.000Z,False,"{'id': '6992160175498986502', 'name': 'aaranth...",{'musicName': 'Path of the Wind (My Neighbor T...,https://www.tiktok.com/@aarantheartist/video/7...,"{'height': 1024, 'width': 576, 'duration': 43,...",...,"[{'name': 'howtodraw'}, {'name': 'arttutotials...",[],False,False,False,[],ghibliart,"{'name': 'ghibliart', 'views': 291600000}",None,NaN
1,7641975211268525333,Paint with me 🎨🌱\nA commission from anime Spir...,en,1779286012,2026-05-20T14:06:52.000Z,False,"{'id': '7556229365740422161', 'name': 'hoongan...","{'musicName': 'original sound', 'musicAuthor':...",https://www.tiktok.com/@hoonganart/video/76419...,"{'height': 1024, 'width': 576, 'duration': 56,...",...,"[{'name': 'hoonganart'}, {'name': 'ghibli'}, {...",[],False,False,False,[],ghibliart,"{'name': 'ghibliart', 'views': 291600000}",None,NaN
2,7246884146465787178,Adding to a painting I found on the street // ...,en,1687296714,2023-06-20T21:31:54.000Z,False,"{'id': '6632070193432985606', 'name': 'lsabell...",{'musicName': 'path of the wind ~ my neighbor ...,https://www.tiktok.com/@lsabellaaddison/video/...,"{'height': 1024, 'width': 576, 'duration': 28,...",...,"[{'name': 'art'}, {'name': 'totoro'}, {'name':...",[],False,False,False,[],ghibliart,"{'name': 'ghibliart', 'views': 291600000}",None,NaN
3,7659048738605894933,Hướng dẫn vẽ đá phong cách Ghibli🎀 Lâu rồi mới...,vi,1783261253,2026-07-05T14:20:53.000Z,False,"{'id': '7556229365740422161', 'name': 'hoongan...","{'musicName': 'Ghibli-style sentimental BGM, a...",https://www.tiktok.com/@hoonganart/video/76590...,"{'height': 1024, 'width': 576, 'duration': 64,...",...,"[{'name': 'hoonganart'}, {'name': 'lobeobrush'...",[],False,False,False,[],ghibliart,"{'name': 'ghibliart', 'views': 291600000}",None,NaN
4,7501537950438591751,‎𓈒 ꒪ ♬ ⋆˚࿔ 𖦤˚ ༘ ೀ⋆｡˚\na video that’s kinda lon...,en,1746587913,2025-05-07T03:18:33.000Z,False,"{'id': '7150564739180643355', 'name': 'happiar...","{'musicName': 'Glue Song', 'musicAuthor': 'SON...",https://www.tiktok.com/@happiartt/video/750153...,"{'height': 1024, 'width': 576, 'duration': 145...",...,"[{'name': 'art'}, {'name': 'artist'}, {'name':...",[],False,False,False,[],ghibliart,"{'name': 'ghibliart', 'views': 291600000}",None,NaN

In [9]:
tiktok_clean = tiktok_df[[
    "searchHashtag",
    "id",
    "text",
    "hashtags",
    "webVideoUrl",
    "diggCount",
    "commentCount",
    "shareCount",
    "playCount",
    "createTimeISO",
    "authorMeta",
    "locationMeta"
]].copy()

tiktok_clean.rename(columns={
    "searchHashtag": "Search Hashtag",
    "id": "Post ID",
    "text": "Caption",
    "hashtags": "Hashtags",
    "webVideoUrl": "Video URL",
    "diggCount": "Likes",
    "commentCount": "Comments",
    "shareCount": "Shares",
    "playCount": "Views",
    "createTimeISO": "Timestamp",
    "authorMeta": "Author",
    "locationMeta": "Location"
}, inplace=True)

tiktok_clean.to_csv(
    "tiktok_ghibli_posts.csv",
    index=False
)

print(f"Saved {len(tiktok_clean)} posts.")

display(tiktok_clean.head())

Saved 400 posts.

,Search Hashtag,Post ID,Caption,Hashtags,Video URL,Likes,Comments,Shares,Views,Timestamp,Author,Location
0,"{'name': 'ghibliart', 'views': 291600000}",7659146694608801027,How to draw in studio ghibli art style. I see ...,"[{'name': 'howtodraw'}, {'name': 'arttutotials...",https://www.tiktok.com/@aarantheartist/video/7...,84,1,1,913,2026-07-05T20:41:05.000Z,"{'id': '6992160175498986502', 'name': 'aaranth...",NaN
1,"{'name': 'ghibliart', 'views': 291600000}",7641975211268525333,Paint with me 🎨🌱\nA commission from anime Spir...,"[{'name': 'hoonganart'}, {'name': 'ghibli'}, {...",https://www.tiktok.com/@hoonganart/video/76419...,5368,37,343,56700,2026-05-20T14:06:52.000Z,"{'id': '7556229365740422161', 'name': 'hoongan...",NaN
2,"{'name': 'ghibliart', 'views': 291600000}",7246884146465787178,Adding to a painting I found on the street // ...,"[{'name': 'art'}, {'name': 'totoro'}, {'name':...",https://www.tiktok.com/@lsabellaaddison/video/...,21300,232,1091,479900,2023-06-20T21:31:54.000Z,"{'id': '6632070193432985606', 'name': 'lsabell...",NaN
3,"{'name': 'ghibliart', 'views': 291600000}",7659048738605894933,Hướng dẫn vẽ đá phong cách Ghibli🎀 Lâu rồi mới...,"[{'name': 'hoonganart'}, {'name': 'lobeobrush'...",https://www.tiktok.com/@hoonganart/video/76590...,904,11,22,7443,2026-07-05T14:20:53.000Z,"{'id': '7556229365740422161', 'name': 'hoongan...",NaN
4,"{'name': 'ghibliart', 'views': 291600000}",7501537950438591751,‎𓈒 ꒪ ♬ ⋆˚࿔ 𖦤˚ ༘ ೀ⋆｡˚\na video that’s kinda lon...,"[{'name': 'art'}, {'name': 'artist'}, {'name':...",https://www.tiktok.com/@happiartt/video/750153...,409500,2084,21300,3300000,2025-05-07T03:18:33.000Z,"{'id': '7150564739180643355', 'name': 'happiar...",NaN

In [10]:
print("Dataset Shape:")
print(tiktok_clean.shape)

print("\nColumns:")
print(tiktok_clean.columns.tolist())

print("\nMissing Values:")
print(tiktok_clean.isnull().sum())

tiktok_clean.describe(include="all")

Dataset Shape:
(400, 12)

Columns:
['Search Hashtag', 'Post ID', 'Caption', 'Hashtags', 'Video URL', 'Likes', 'Comments', 'Shares', 'Views', 'Timestamp', 'Author', 'Location']

Missing Values:
Search Hashtag      0
Post ID             0
Caption             0
Hashtags            0
Video URL           0
Likes               0
Comments            0
Shares              0
Views               0
Timestamp           0
Author              0
Location          370
dtype: int64

,Search Hashtag,Post ID,Caption,Hashtags,Video URL,Likes,Comments,Shares,Views,Timestamp,Author,Location
count,400,400,400,400,400,4.000000e+02,400.00000,400.000000,4.000000e+02,400,400,30
unique,4,386,380,364,386,NaN,NaN,NaN,NaN,386,326,27
top,"{'name': 'ghibliart', 'views': 291600000}",7487381483850648875,#ghiblistyle\n#ghibliaesthetic\n#animevibes\n#...,[],https://www.tiktok.com/@yungpicari/video/74873...,NaN,NaN,NaN,NaN,2025-03-29T23:44:41.000Z,"{'id': '7119816872937784326', 'name': 'stvligh...","{'address': 'Vietnam', 'city': 'Ho Chi Minh Ci..."
freq,100,2,6,8,2,NaN,NaN,NaN,NaN,2,15,2
mean,NaN,NaN,NaN,NaN,NaN,8.349190e+04,352.60250,5273.655000,6.053189e+05,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,2.627510e+05,1037.66548,19470.411907,1.674962e+06,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,2.000000e+00,0.00000,0.000000,7.700000e+01,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,2.477500e+02,7.00000,17.000000,4.367250e+03,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,3.689500e+03,32.00000,195.000000,5.865000e+04,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,4.057500e+04,204.75000,1875.500000,3.703250e+05,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,2.500000e+06,11700.00000,214500.000000,1.840000e+07,NaN,NaN,NaN

## Conclusion

Public TikTok posts related to the selected hashtags were successfully collected using the Apify TikTok Hashtag Scraper.

The dataset has been cleaned, inspected, and exported for future analysis as part of the GenAI Carbon Footprint Research Project.